### PR TITLE
[#282] Support running new_project.kts from project root folder

### LINKED ISSUE #282: Fix: Can't run the script from the ROOT folder
## Issue

Currently, the steps to set up the project are wrong. I can't set up the project from the root folder. Only can when I move to the scripts folder. I think we should support the run the script from the ROOT folder.

Screen Shot 2022-08-22 at 18 05 21

## Expected

Can set up the project normally with `kscript scripts/new_project.kts`.

## Steps to reproduce

1. Clone the project
2. Run the script: `kscript scripts/new_project.kts package-name=co.nimblehq.test app-name=Test`
3. Can't setup the project

### PR DESCRIPTION
**Pull request by ryan-conway**
Closes #282 

## What happened 👀

Fixed issue with `new_project.kts` not running properly from root folder.
Also fixed issue when generating a new project and file path contains `scripts` anywhere before the last segment.

## Insight 📝

- Added check if current directory ends with `/scripts`
- If yes, remove last segment.
- If no, keep path as is and append `/`

## Proof Of Work 📹

Note: PoW captured by printing `rootPath`, `projectPath` and `ProjectFolderName` values

Old script from path that contains `script`
Screenshot 2565-08-24 at 14 46 01

New script from path that contains `scripts`
Screenshot 2565-08-24 at 14 46 30

New script from root folder
Screenshot 2565-08-24 at 14 48 35

New script from `/scripts` folder
Screenshot 2565-08-24 at 14 48 43

### CODE REVIEW

**Comment by Wadeewee** [comment]
@ryan-conway It would be nice If we update the `helpMessage.` to support the new script🤗

**Comment by ryan-conway** [comment]
> @ryan-conway It would be nice If we update the `helpMessage` to support the new script.🤗

@Wadeewee Good catch 😄 How about the following? What do you think? 🤔 
```
        Run kscript new_project.kts to create a new project with the following arguments:
            package-name=   New package name (i.e., com.example.package)
            app-name=       New app name (i.e., MyApp, "My App", "my-app")
        
        Examples: 
            kscript new_project.kts package-name=co.myproject.example app-name="My Project"
            kscript scripts/new_project.kts package-name=co.myproject.example app-name="My Project"
```

File: scripts/new_project.kts [hunk 1]
```diff
@@ -59,7 +59,13 @@ object NewProject {
         get() = rootPath + projectFolderName
 
     private val rootPath: String
-        get() = System.getProperty("user.dir").replace("scripts", "")
+        get() = System.getProperty("user.dir").let { userDir ->
+            if (userDir.endsWith("/scripts")) {
```
Comment (Wadeewee) [inline scripts/new_project.kts:63]: Let's use `SEPARATOR_SLASH`:
```suggestion
            if (userDir.endsWith("${SEPARATOR_SLASH}scripts")) {
```

File: scripts/new_project.kts [hunk 2]
```diff
@@ -59,7 +59,13 @@ object NewProject {
...
+                userDir.substring(0, userDir.lastIndexOf("scripts"))
+            } else {
+                userDir + "/"
```
Comment (Wadeewee) [inline scripts/new_project.kts:66]: Same here:
```suggestion
                "$userDir$SEPARATOR_SLASH"
```

**Comment by Wadeewee** [comment]
> > @ryan-conway It would be nice If we update the `helpMessage` to support the new script.🤗
> 
> @Wadeewee Good catch 😄 How about the following? What do you think? 🤔
> 
> ```
>         Run kscript new_project.kts to create a new project with the following arguments:
>             package-name=   New package name (i.e., com.example.package)
>             app-name=       New app name (i.e., MyApp, "My App", "my-app")
>         
>         Examples: 
>             kscript new_project.kts package-name=co.myproject.example app-name="My Project"
>             kscript scripts/new_project.kts package-name=co.myproject.example app-name="My Project"
> ```

Good to me @ryan-conway 🚀

File: scripts/new_project.kts (hunk 1 above)
Comment (manh-t) [reply scripts/new_project.kts:63]: @Wadeewee I think we agreed to use `File.separator` to handle the issue with Window platform that the separator will be `\` instead of `/`. 😅 And we already define `private val fileSeparator = File.separator` in [line 34 ](https://github.com/nimblehq/android-templates/pull/287/files#diff-7eb696319d9f663e727291b14010369b88a196561c3982f204666a5f53df43b9R34), so `SEPARATOR_SLASH` might be redundant in this case. Please correct me if I'm wrong 🙇

Comment (Wadeewee) [reply scripts/new_project.kts:63]: Oh, yeah @manh-t 👍  Thank for reminding me 🙏 Then we can use `fileSeparator` instead of `SEPARATOR_SLASH` cc @ryan-conway

File: scripts/new_project.kts [hunk 3]
```diff
@@ -26,7 +28,9 @@ object NewProject {
             package-name=   New package name (i.e., com.example.package)
             app-name=       New app name (i.e., MyApp, "My App", "my-app")
         
-        Example: kscript new_project.kts package-name=co.myproject.example app-name="My Project"
+        Examples:
```
Comment (chornerman) [inline scripts/new_project.kts:31]: Redundant space 😄 
```suggestion
        Examples:
```

**Review by chornerman — COMMENTED** [review]
The rest LGTM 🚀

**Review by chornerman — APPROVED** [review]
lgtm 🚀

**Review by manh-t — APPROVED** [review]
LGTM 🚀

**Review by Wadeewee — APPROVED** [review]
