### PR TITLE
[#273] Fix incorrect step for running tests in `new_project.kts`

### LINKED ISSUE #273: Fix incorrect step for running tests in `new_project.kts`
## Issue

When running `testStagingDebugUnitTest`, it only executes the tests for `:app` module

## Expected

When running `jacocoTestReport`, it executes the tests for `:app`, `:domain` & `:data` module

## Steps to reproduce

1. Run `new_project.kts`
2. Observe logs

### PR DESCRIPTION
**Pull request by Tuubz**
Closes #273

## What happened 👀

`testStagingDebugUnitTest` only executes tests for `app` module, so execute command for each module separately

## Proof Of Work 📹

Please check "Verify generating new project from template" logs
https://github.com/nimblehq/android-templates/runs/7893007827?check_suite_focus=true

### CODE REVIEW

**Comment by chornerman** [comment]
@Tuubz Conflict 🦀

**Review by chornerman — APPROVED** [review]
@Tuubz Do we have any POW for this PR? 🙏🏼

**Review by ryan-conway — APPROVED** [review]

File: scripts/new_project.kts [hunk 1]
```diff
@@ -248,7 +248,7 @@ object NewProject {
             "$projectPath${fileSeparator}gradlew",
             "-p",
             "$projectPath",
-            "testStagingDebugUnitTest"
+            "jacocoTestReport"
```
Comment (sleepylee) [inline scripts/new_project.kts:251]: I have mixed feeling of this solution 🤔 what if we don't use jacoco anymore, given that there is Kover on the corner waiting for the evaluation 🤔

Comment (Tuubz) [reply scripts/new_project.kts:251]: `testStagingDebugUnitTest` is only running tests for `app` module, hence the update

If we end up using Kover, we can always adapt it again later 🚀

Comment (sleepylee) [reply scripts/new_project.kts:251]: have you tried just `test` or `testStagingDebug`? I think jacoco must run a similar gradle command under the hood, so probably you can sneak into the gradle log to see what has been called. Running jacocoTestReport is slower and you are not going to read the report at the time you init the project right?

Comment (Tuubz) [reply scripts/new_project.kts:251]: @sleepylee You're right, `jacocoTestReport` should be avoided, as we won't be reading the report 👍 

Unfortunately, I can't make it work with other commands:
- `test` : Executes tests for both `debug` & `release` variant too, which should be avoided
- `testStagingDebug` : Only runs tests for `app` module
- `testDebugUnitTest` : Only runs tests for `data` module

Maybe something is wrong with our set-up 💭 

Screen Shot 2565-08-18 at 12 32 18

Comment (sleepylee) [reply scripts/new_project.kts:251]: @Tuubz seems like it's possibly because we don't have `staging` flavor in `data`, so perhaps we can execute 2 commands:
```
testStagingDebug -> this ensure any module that has Staging flavor will run unit test
testDebugUnitTest -> any module that does not have extra flavor, must run the debug build type
```

pros: 
 - you don't need to think about this again when moving to Kover or any other coverage report tools, or even if we remove it entirely.
cons:
 - 🤔

Comment (Tuubz) [reply scripts/new_project.kts:251]: @sleepylee thanks for the feedback, I'll go with your suggestion.

I think we'll end up needing to execute 3 commands (`app`, `data` & `domain`)

Comment (sleepylee) [reply scripts/new_project.kts]: 🤔  @Tuubz correct me if I'm wrong but doesn't `testDebugUnitTest` execute `:data` AND `:domain`?

Comment (Tuubz) [reply scripts/new_project.kts]: @sleepylee No, it only runs for `:data` 😞

File: scripts/new_project.kts [hunk 2]
```diff
@@ -248,7 +248,21 @@ object NewProject {
             "$projectPath${fileSeparator}gradlew",
             "-p",
             "$projectPath",
-            "testStagingDebugUnitTest"
+            ":app:testStagingDebugUnitTest"
```
Comment (sleepylee) [inline scripts/new_project.kts:251]: then possibly you can use `&` instead of 3 executeCommand?

```suggestion
            ":app:testStagingDebugUnitTest & :data:testDebugUnitTest & :domain:test"
```

Comment (Tuubz) [reply scripts/new_project.kts]: @sleepylee Thanks for the suggestion, looks a lot better now

Thank you 🎸

**Review by sleepylee — APPROVED** [review]
