### PR TITLE
[#269] Fix file path error when executing new_project.kts

### LINKED ISSUE #269: Fix file path error when executing new_project.kts
## Issue

The `new_projects.kts` script executes file operations (copy, remove, ...) and Gradle commands, by referencing _local file paths_

So when the script runs `cleanNewProjectFolder()` with the following path, it fails:

> sh Users/lydiasama/Nimble/**My Projects**/android-templates/sample-xml/gradlew -p

This is because **My Projects** includes a space!

## Expected

A possible solution would be something like this:

> sh Users/lydiasama/Nimble/*"My Projects"*/android-templates/sample-xml/gradlew -p

So we wrap "**My Projects**" with quotes!

## Steps to reproduce

1. Add a white space to a folder in the file path
2. Run script as usual

Reference: https://nimble-co.slack.com/archives/G41UCTGHL/p1659600390526129

### PR DESCRIPTION
**Pull request by Tuubz**
Closes #269 

## What happened 👀
`Runtime.getRuntime().exec(String)` will partition a command automatically, based on white spaces.
If a file path contains a white space, it will not be able to find the file and result in an error.
     
-> **Example**: "Desktop/My Projects/android-templates" -> ["Desktop/My", "Projects/android-templates"]
-> **Reference**: https://stackoverflow.com/questions/33077129/java-runtime-exec-with-white-spaces-on-path-name

## Insight 📝

Preferably I don't want to pass an array of Strings, so initially, so I tried the following:

- I tried escaping the white space (`\`)
- I tried encoding the white space (`%20)`
- I tried wrapping the file path with quotes
- I tried splitting up the command into an array, with regular expressions

Unfortunately, I couldn't make it work with these approaches

Please let me know if anyone has a better solution 🙏 

## Proof Of Work 📹

Script can run successfully if file path contains a white space:
https://user-images.githubusercontent.com/18277915/184601355-6352ca8e-4d8b-466f-8130-a33b4c8ee384.mov

### CODE REVIEW

File: scripts/new_project.kts [hunk 1]
```diff
@@ -238,9 +270,21 @@ object NewProject {
...
+     *
+     * Runtime.getRuntime().exec(String) will partition a command automatically, based on white spaces.
+     * If a file path contains a white space, it will not be able to find the file and result in an error.
+     *
+     * -> Example: "Desktop/My Projects/android-templates" -> ["Desktop/My", "Projects/android-templates"]
+     * -> Reference: https://stackoverflow.com/questions/33077129/java-runtime-exec-with-white-spaces-on-path-name
+     *
+     * @param [command]: A command partioned in to an array of strings
+     */
+    private fun executeCommand(command: Array<String>) {
```
Comment (ryan-conway) [inline scripts/new_project.kts:284]: How about setting the argument as a `vararg`? We might be able to shorten the calls to this method by not creating an array explicitly, what do you think? 🤔 
```suggestion
    private fun executeCommand(vararg command: String) {
```
And calls could look like
```kotlin
executeCommand(
    "sh",
    "$projectPath${fileSeparator}gradlew",
    "-p",
    "$projectPath",
    "clean"
)

File: scripts/new_project.kts [hunk 2]
```diff
@@ -238,9 +270,21 @@ object NewProject {
...
+    /**
+     * Execute a shell command
+     *
+     * Runtime.getRuntime().exec(String) will partition a command automatically, based on white spaces.
+     * If a file path contains a white space, it will not be able to find the file and result in an error.
+     *
+     * -> Example: "Desktop/My Projects/android-templates" -> ["Desktop/My", "Projects/android-templates"]
+     * -> Reference: https://stackoverflow.com/questions/33077129/java-runtime-exec-with-white-spaces-on-path-name
+     *
+     * @param [command]: A command partioned in to an array of strings
```
Comment (chornerman) [inline scripts/new_project.kts:282]:
```suggestion
     * @param [command]: A command partitioned into an array of strings
```

**Review by chornerman — COMMENTED** [review]
Just some typos 😄

**Comment by Tuubz** [comment]
@ryan-conway @chornerman Updated 🚀

**Review by ryan-conway — APPROVED** [review]
LGTM 👍🏻

File: scripts/new_project.kts [hunk 3]
```diff
@@ -238,9 +262,22 @@ object NewProject {
...
+     * Execute a shell command
+     *
+     * Runtime.getRuntime().exec(String) will partition a command automatically, based on white spaces.
+     * If a file path contains a white space, it will not be able to find the file and result in an error.
+     * 
+     * Example: "Desktop/My Projects/android-templates" -> ["Desktop/My", "Projects/android-templates"]
+     * Solution: Partition the command before being passing it to Runtime.getRuntime().exec(String)
+     * Reference: https://stackoverflow.com/questions/33077129/java-runtime-exec-with-white-spaces-on-path-name
+     *
+     * @param [command]: A command partioned into multiple arguments
```
Comment (chornerman) [inline scripts/new_project.kts:275]:
```suggestion
     * @param [command]: A command partitioned into multiple arguments
```

File: scripts/new_project.kts [hunk 4]
```diff
@@ -238,9 +262,22 @@ object NewProject {
         }
     }
 
-    private fun executeCommand(command: String) {
+    /**
+     * Execute a shell command
+     *
+     * Runtime.getRuntime().exec(String) will partition a command automatically, based on white spaces.
+     * If a file path contains a white space, it will not be able to find the file and result in an error.
+     *
```
Comment (chornerman) [inline scripts/new_project.kts:270]: I think adding this space is redundant 😄 

Screen Shot 2565-08-16 at 11 33 27

File: scripts/new_project.kts [hunk 5]
```diff
@@ -238,9 +262,22 @@ object NewProject {
...
 
-    private fun executeCommand(command: String) {
+    /**
+     * Execute a shell command
+     *
+     * Runtime.getRuntime().exec(String) will partition a command automatically, based on white spaces.
+     * If a file path contains a white space, it will not be able to find the file and result in an error.
+     * 
+     * Example: "Desktop/My Projects/android-templates" -> ["Desktop/My", "Projects/android-templates"]
+     * Solution: Partition the command before being passing it to Runtime.getRuntime().exec(String)
```
Comment (chornerman) [inline scripts/new_project.kts:272]: Please correct me if I'm wrong 🙏🏼 
```suggestion
     * Solution: Partition the command before passing it to Runtime.getRuntime().exec(String)
```

**Review by chornerman — COMMENTED** [review]
Some more on the comment 🙏🏼

**Comment by Tuubz** [comment]
@chornerman Thank you 🐝

**Review by chornerman — APPROVED** [review]
LGTM 🚀

File: scripts/new_project.kts [hunk 6]
```diff
@@ -238,9 +262,22 @@ object NewProject {
         }
     }
 
-    private fun executeCommand(command: String) {
+    /**
+     * Execute a shell command
+     *
+     * Runtime.getRuntime().exec(String) will partition a command automatically, based on white spaces.
+     * If a file path contains a white space, it will not be able to find the file and result in an error.
```
Comment (lydiasama) [inline scripts/new_project.kts:269]: How about generally this a bit?
```suggestion
     * If a file path contains any white spaces, it will not be able to find the file and result in an error.
```

**Review by lydiasama — COMMENTED** [review]
The rest LGTM

File: scripts/new_project.kts (hunk 6 above)
Comment (Tuubz) [reply scripts/new_project.kts]: @lydiasama Updated 😁

**Review by lydiasama — APPROVED** [review]
