### PR TITLE
[#346] Fix failing sample xml test

### LINKED ISSUE #346: Fix failing test in sample-xml
## Issue

The unit test in `HomeFragmentTest` in the `sample-xml` project won't compile as there is no reference to `tvTitle` anymore. 
Robolectric also needs to be updated as per [this issue](https://github.com/nimblehq/android-templates/issues/304).

## Expected

Tests should run as expected.

## Steps to reproduce

1. Open `sample-xml`
2. Attempt to run tests in `HomeFragmentTest`

### PR DESCRIPTION
**Pull request by Tuubz**
Closes #346 

## What happened 👀

- Fix failing `HomeFragmentTest.kt` in `sample-xml`
- Update robolectrics versions for sample projects so it aligned with `template`

## Proof Of Work 📹

Screen Shot 2022-11-14 at 11 20 23

### CODE REVIEW

File: sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/xml/HomeFragmentTest.kt [hunk 1]
```diff
@@ -28,9 +28,9 @@ class HomeFragmentTest : BaseFragmentTest<HomeFragment, FragmentHomeBinding>() {
     }
 
     @Test
-    fun `When initializing fragment, it displays the title correctly`() {
+    fun `When initializing fragment, it displays the recycler-view`() {
```
Comment (ryan-conway) [inline sample-xml/app/src/test/java/co/nimblehq/sample/xml/ui/screens/xml/HomeFragmentTest.kt:31]: The hyphen feels weird to me, perhaps `recycler view` instead? What do you think?
The rest LGTM 👌🏻

**Review by ryan-conway — APPROVED** [review]
🙏🏻

**Review by doannimble — APPROVED** [review]

**Comment by Tuubz** [comment]
@nimblehq/android-chapter Could we get one more approval here, please? It's a small quick fix 🙇

**Review by sleepylee — APPROVED** [review]
