### PR TITLE
[#275] Fix references when generating a new project

### LINKED ISSUE #275: Fix references when generating a new project
## Issue

Some files are not updated correctly when generating a new project

## Expected
The following files must be updated accordingly when generating a new project:
- Update `signing.properties` path in `README.md` 
- Update `applicationId` in `build.gradle.kts` 
- Update `packagesExcluded` in `jacoco-report.gradle.kts` 
- Remove `### Android template` from `.gitignore`

## Steps to reproduce

1. Generate a new project
2. Observe files as specified above

### PR DESCRIPTION
**Pull request by Tuubz**
Closes #275

## What happened 👀

- Update forgotten files when running `new_project.kts`:

  - `app/build.gradle.kts` : Rename package name in `applicationId`
  - `jacoco-report.gradle.kts` : Rename package name in `packagesExcluded`
- Refactor `SEPARATOR` const variables so they can be grouped
- Clean up `README.md`: To keep it simple, just remove the link
- Clean up `.gitignore`

## Proof Of Work 📹

https://user-images.githubusercontent.com/18277915/184790619-1a4b155d-8d24-4d07-bc5f-bfc9db217da3.mp4

### CODE REVIEW

File: scripts/new_project.kts [hunk 1]
```diff
@@ -189,13 +190,25 @@ object NewProject {
         showMessage("=> 🔎 Renaming package name within files...")
         File(projectPath)
             .walk()
-            .filter { it.name.endsWith(".kt") || it.name.endsWith(".xml") }
+            .filter {
+                it.name.endsWith(".kt")
+                        || it.name.endsWith(".xml")
+                        || it.name.endsWith(".gradle.kts")
```
Comment (chornerman) [inline scripts/new_project.kts:196]: Could you please help recheck if these lines are indented correctly 🙏🏼

**Review by chornerman — APPROVED** [review]
The rest LGTM 🎉

File: scripts/new_project.kts (hunk 1 above)
Comment (Tuubz) [reply scripts/new_project.kts:196]: I don't like it too, but nothing after I auto-format 🙈 

What about you?

Comment (chornerman) [reply scripts/new_project.kts:196]: Mine look like this after auto-format 🙈 

Screen Shot 2565-08-16 at 10 45 27

Comment (chornerman) [reply scripts/new_project.kts:196]: Conclusion: From our Compass, we will use 8 space indent for line wraps, therefore, the current indent is correct. Thanks @Tuubz 

Screen Shot 2565-08-16 at 10 53 41

Comment (ryan-conway) [reply scripts/new_project.kts:196]: [Optional] If it really bothers you, we could write a helper method for it 🤔 
```kotlin
private fun String.endsWithAny(vararg suffixes: String): Boolean {
    for (suffix in suffixes) if endsWith(suffix) return true
    return false
}

File(projectPath)
    .walk()
    .filter { it.name.endsWithAny(".kt", ".xml", ".gradle.kts") }
```

Comment (Tuubz) [reply scripts/new_project.kts]: @ryan-conway Updated 🤖

**Review by ryan-conway — APPROVED** [review]

**Review by sleepylee — APPROVED** [review]

File: scripts/new_project.kts [hunk 2]
```diff
@@ -3,14 +3,15 @@ import java.io.File
...
     private const val ARGUMENT_DELIMITER = "="
-    private const val DOT_SEPARATOR = "."
     private const val KEY_APP_NAME = "app-name"
     private const val KEY_HELP = "--help"
     private const val KEY_PACKAGE_NAME = "package-name"
-    private const val MINUS_SEPARATOR = "-"
     private const val PATTERN_APP = "^([A-Z][a-zA-Z0-9\\s]*)|([a-z][a-z0-9-]*)$"
     private const val PATTERN_PACKAGE = "^[a-z]+(\\.[a-z][a-z0-9]*)+$"
-    private const val SPACE_SEPARATOR = " "
+    private const val SEPARATOR_DOT = "."
```
Comment (lydiasama) [inline scripts/new_project.kts:11]: These SEPARATOR constants have become many more now. How about adding a break-line before and after for grouping them? Same thought as other constants too.

File: scripts/new_project.kts [hunk 3]
```diff
@@ -189,13 +190,21 @@ object NewProject {
         showMessage("=> 🔎 Renaming package name within files...")
         File(projectPath)
             .walk()
-            .filter { it.name.endsWith(".kt") || it.name.endsWith(".xml") }
+            .filter { it.name.endsWithAny(".kt", ".xml", ".gradle.kts") }
```
Comment (lydiasama) [inline scripts/new_project.kts:193]: Nice refactoring 👍🏻

File: scripts/new_project.kts [hunk 4]
```diff
@@ -189,13 +190,21 @@ object NewProject {
...
             .forEach { filePath ->
-                rename(
-                    sourcePath = filePath.toString(),
-                    oldValue = TEMPLATE_PACKAGE_NAME,
-                    newValue = packageName
-                )
+                if (filePath.name == "jacoco-report.gradle.kts") {
```
Comment (lydiasama) [inline scripts/new_project.kts:195]: Can we use `when(filePath.name)` for this if block? 🤔

Comment (Tuubz) [reply scripts/new_project.kts]: @lydiasama Updated 💯

**Comment by Tuubz** [comment]
@lydiasama Any last comments before we merge this pull request? 😁

**Review by minhnimble — APPROVED** [review]

**Review by AVI5HEK — APPROVED** [review]

**Review by Wadeewee — APPROVED** [review]

**Review by lydiasama — APPROVED** [review]
